### ISSUE TITLE
Layer no longer public ?

### ISSUE THREAD

**Issue by tomchiverton** [shivtej1505/phantom-js-lambda-layer#1]
# aws lambda get-layer-version-by-arn --arn arn:aws:lambda:eu-west-1:699054759624:layer:phantom-js:1 --query Content.Location --output text

An error occurred (AccessDeniedException) when calling the GetLayerVersionByArn operation: User: arn:aws:iam::yyyy:user/xxx is not authorized to perform: lambda:GetLayerVersion on resource: arn:aws:lambda:eu-west-1:699054759624:layer:phantom-js:1

**Comment by shivtej1505** [comment]
Hey @tomchiverton , this was totally unintentional.
They were public a while ago. I have to check once.

**Comment by tomchiverton** [comment]
Still failing...

**Comment by shivtej1505** [comment]
Hey @tomchiverton 
I think I figured the issue. I was not giving `--region` flag while giving layer permission.
I think you also must give `--region` flag here with `eu-west-1` option to access it

**Comment by tomchiverton** [comment]
Ack. Seems OK now
